name: 'Fetch crate'
author: 'lmaotrigine'
description: 'Install any Rust crate'
branding:
  icon: 'settings'
  color: 'red'
inputs:
  owner:
    required: true
    description: 'The GitHub user or organization'
  name:
    required: true
    description: 'The GitHub repository name'
  version:
    required: false
    description: 'A valid semver specifier of the crate version to install'
  github-token:
    required: false
    description: 'The GitHub token used for making API requests'
    default: ${{ github.token }}
  bin:
    required: false
    description: 'The name of the binary to extract, defaults to the crate name'
runs:
  using: 'node16'
  main: 'dist/index.js'
